# -*- coding: utf-8 -*-
"""hash.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RCd47vq0DDmp130Oy-qUxxlI9NBcwdMW
"""

import hashlib
import binascii
import time

def main():
    #data = 'a' * 256
    #data = 'a' * 512
    #data = 'a' * 1024
    data = 'a' * 2048
        
    start = time.time()
    for i in range(1000):
        key = hashlib.sha256(data).digest()
    
    #print "sha256: " + binascii.hexlify(bytearray(key))
    stop = time.time() - start
    
    print('sha256 1000 times: ' + str(stop))

    start = time.time()
    for i in range(1000):
        key = hashlib.sha512(data).digest()
    
    #print "sha512: " + binascii.hexlify(bytearray(key))
    stop = time.time() - start
    
    print('sha512 1000 times: ' + str(stop))
    
main()